name: Clean Project
on: workflow_dispatch # یہ بٹن دبانے پر چلے گا

jobs:
  wipe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          # .git اور .github کے علاوہ سب کچھ مٹا دو
          find . -maxdepth 1 ! -name '.git' ! -name '.github' ! -name '.' -exec rm -rf {} +
          git config user.name "Cleaner"
          git config user.email "cleaner@github.com"
          git add .
          git commit -m "All files removed"
          git push
