name: Auto-Fix and Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java and Flutter
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Recreate Android Project (The 1-Minute Fix)
        run: |
          # 1. پرانا خراب اینڈرائیڈ فولڈر جڑ سے ختم کرنا
          rm -rf android
          
          # 2. فلٹر کو کہنا کہ نیا اور لیٹسٹ اینڈرائیڈ فولڈر خود بناؤ
          flutter create . --platforms android
          
          # 3. آپ کا پیکج نیم (Package Name) سیٹ کرنا
          # یہ لائن آپ کے ایپ کی شناخت کو برقرار رکھے گی
          sed -i 's/com.example.premium_chat/com.quick.designapp/g' android/app/build.gradle
          
      - name: Build Optimized APK
        run: |
          flutter pub get
          flutter build apk --release --target-platform android-arm64 --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PremiumChat-Fresh-Build
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
