name: Deploy Web (Manual APK)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # اس سے "Run Workflow" کا بٹن ظاہر ہوگا

permissions:
  pages: write
  id-token: write
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Install Dependencies
        run: flutter pub get

      # ویب بلڈ (یہ ہر بار پش پر چلے گی)
      - name: Build Web
        run: flutter build web --pwa-strategy=none --base-href "/Premium-chat/"

      - name: Upload Web Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # اے پی کے بلڈ (یہ صرف تب چلے گی جب آپ مینوئلی بٹن دبائیں گے)
      - name: Build APK (Manual Only)
        if: github.event_name == 'workflow_dispatch'
        run: flutter build apk --release --split-per-abi

      - name: Upload APK Artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: Premium-Chat-App
          path: build/app/outputs/flutter-apk/app-release.apk 
